depth = 50;
event_inherited();
tv_do_expression(spr_tv_exprcollect, true);
image_speed = 0.35;
yoffset = 0;
hsp = 0;
vsp = 0;
grav = 0.23;
movespeed = 3;
panic = false;
playerid = obj_player1;
state = states.normal;
spr_intro = sprite_index;
spr_run = sprite_index;
spr_idle = sprite_index;
spr_panic = sprite_index;
spr_taunt = sprite_index;
spr_intro_strongcold = sprite_index;
spr_run_strongcold = sprite_index;
spr_idle_strongcold = sprite_index;
xprev = x;
yprev = y;
