image_speed = 0;
image_index = 0;
solidID = instance_create(x, y, obj_solid);
solidID.sprite_index = sprite_index;
solidID.visible = false;
solidID.image_speed = 0;
solidID.image_xscale = image_xscale;
solidID.image_yscale = image_yscale;
active = false;
