event_inherited();
player_distance_threshold = 500;
ghost_distance_threshold = 400;
state = states.normal;
hsp = 0;
vsp = 0;
hsp_carry = 0;
vsp_carry = 0;
platformid = -4;
grounded = false;
grav = 0.5;
alarm[1] = 1;
