event_inherited();
depth = 1;
trigger = 1;
idlespr = spr_menutv2_idle;
transspr = spr_menutv2_trans;
confirmspr = spr_menutv2_confirm;
selectedspr = spr_menutv2_selected;
clipspr = spr_menutv2_clip;
noisescale = 0.6;
noisexoffset = 38;
noiseyoffset = 58;
