scr_initenemy()
usepalette = 1
is_controllable = 1
possess_movespeed = 0
gusrat = 0
grav = 0.5
hsp = 0
vsp = 0
state = states.walk
stunned = 0
alarm[0] = 150
roaming = 1
collectdrop = 5
flying = 0
straightthrow = 0
cigar = 0
cigarcreate = 0
stomped = 0
shot = 0
reset = 0
flash = 0
var _hurt = obj_player1.spr_hurt
var _dead = obj_player1.spr_dead
if obj_player1.isgustavo
{
    _hurt = 3968
    _dead = 2207
}
landspr = _hurt
idlespr = _hurt
fallspr = _hurt
stunfallspr = _hurt
walkspr = _hurt
turnspr = _hurt
recoveryspr = _hurt
grabbedspr = _hurt
scaredspr = _hurt
ragespr = _hurt
image_xscale = -1
hp = 1
slapped = 0
grounded = 1
birdcreated = 0
boundbox = 0
spr_dead = _dead
important = 1
heavy = 0
depth = 0
paletteselect = 0
spr_palette = palette_cheeseslime
sprite_index = spr_slimemove
grabbedby = 0
stuntouchbuffer = 0
scaredbuffer = 0
snotty = 0
