audio_select = 0;
audiosaved_master = global.option_master_volume * 100;
audiosaved_music = global.option_music_volume * 100;
audiosaved_sfx = global.option_sfx_volume * 100;
selecting = -1;
player = 0;
scr_init_input();
stickpressed = false;
key_buffer = 0;
key_max = 5;
updown_buffer = 0;
updown_max = 10;
depth = -100;
