image_speed = 0.35;
hsp = 0;
vsp = 0;
grav = 0.5;
image_xscale = sign(obj_player.x - x);
instance_create(x, y, obj_bangeffect);
drop = false;
alarm[0] = 50;
platformid = -4;
hsp_carry = 0;
vsp_carry = 0;
