hsp = 0;
vsp = 0;
hsp_carry = 0;
vsp_carry = 0;
platformid = -4;
grav = 0.5;
grounded = false;
movespeed = 8;
step_sound = false;
event_inherited();
state = states.robotidle;
use_hallway = true;
idlespr = spr_monstershroom_idle;
walkspr = spr_monstershroom_walk;
chasespr = spr_monstershroom_chase;
yscale = 1;
steppy = false;
