image_speed = 0.35;
playerid = obj_null;
hsp = 0;
vsp = 0;
grav = 0;
dust = 0;
targetDoor = "A";
depth = 10;
escape = false;
police = false;
move = false;
police_buffer = 0;
scr_create_uparrowhitbox();
