/// @description load banks / define sounds.
var maxChannels = 256;
trace("Initializing FMOD: ", fmod_init(maxChannels));
fmod_set_num_listeners(1);

var plat = "Desktop";
var banks = [concat("sound/", plat, "/Master.bank"), concat("sound/", plat, "/music.bank"), concat("sound/", plat, "/sfx.bank"), concat("sound/", plat, "/Master.strings.bank")];
trace("Loading banks! Platform -> ", plat);
for (var i = 0; i < array_length(banks); i++)
{
	var b = working_directory + banks[i];
	trace("Loading bank at: ", b);
	if (!fmod_bank_load(b, false))
		trace("Could not load bank: ", b);
}
global.sound_map = ds_map_create();
global.steam_api = false;
global.screenshotcount = 0;

#region macros

// function aliases
#macro sound_play fmod_event_one_shot // event (string)
#macro sound_play_3d fmod_event_one_shot_3d // event (string), x, y
#macro sound_get_length fmod_event_get_length // event (string)
#macro sound_pause_all fmod_event_instance_set_paused_all // enabled (bool)
// pauses ALL sounds.
#macro sound_set_parameter fmod_set_parameter // parameter (string), value (double), instant (bool)
// sets global parameter.
#macro sound_get_parameter fmod_get_parameter // parameter (string)
// gets global parameter.

#macro sound_instance_create fmod_event_create_instance // event (string)
// returns sound instance (number)
#macro sound_instance_destroy fmod_event_instance_release // sound instance
#macro sound_instance_play fmod_event_instance_play // sound instance
#macro sound_instance_stop fmod_event_instance_stop // sound instance, force (bool)
#macro sound_instance_move fmod_event_instance_set_3d_attributes // sound instance, x, y
#macro sound_instance_set_parameter fmod_event_instance_set_parameter // sound instance, parameter, value, instant
#macro sound_instance_get_parameter fmod_event_instance_get_parameter // sound instance, parameter
#macro sound_instance_is_playing fmod_event_instance_is_playing // sound instance
#macro sound_instance_pause fmod_event_instance_set_paused // sound instance, enabled (bool)
#macro sound_instance_is_paused fmod_event_instance_get_paused // sound instance
#macro sound_instance_track_position fmod_event_instance_get_timeline_pos // sound instance
// returns in milliseconds
#macro sound_instance_set_track_position fmod_event_instance_set_timeline_pos // sound instance, position (milliseconds)

// sounds
#macro sfx_step "event:/sfx/ui/step"
#macro sfx_select "event:/sfx/ui/select"
#macro sfx_back "event:/sfx/ui/back"
#macro sfx_slidersfxmaster "event:/sfx/ui/slidersfxmaster"
#macro sfx_slidermusic "event:/sfx/ui/slidermusic"
#macro sfx_slidersfx "event:/sfx/ui/slidersfx"
#macro sfx_angelmove "event:/sfx/ui/angelmove"
#macro sfx_rankup "event:/sfx/ui/rankup"
#macro sfx_rankdown "event:/sfx/ui/rankdown"
#macro sfx_comboup "event:/sfx/ui/comboup"
#macro sfx_wartimer "event:/sfx/ui/wartimer"
#macro sfx_wartimerup "event:/sfx/ui/wartimerup"
#macro sfx_tvstatic "event:/sfx/ui/tvstatic"
#macro sfx_tvswitch "event:/sfx/ui/tvswitch"
#macro sfx_tvswitchback "event:/sfx/ui/tvswitchback"
#macro sfx_lightswitch "event:/sfx/ui/lightswitch"
#macro sfx_fileselect "event:/sfx/ui/fileselect"
#macro sfx_percentagemove "event:/sfx/ui/percentagemove"

#macro sfx_voice_peppinoangryscream "event:/sfx/voice/peppinoangryscream"
#macro sfx_voice_peppinoangryscream2 "event:/sfx/voice/peppinoangryscream2"
#macro sfx_voice_noisepositive "event:/sfx/voice/noisepositive"
#macro sfx_voice_noisenegative "event:/sfx/voice/noisenegative"
#macro sfx_voice_noisescream "event:/sfx/voice/noisescream"
#macro sfx_voice_gushurt "event:/sfx/voice/gushurt"
#macro sfx_voice_ok "event:/sfx/voice/ok"
#macro sfx_voice_vigiintro "event:/sfx/voice/vigiintro"
#macro sfx_voice_vigiduel "event:/sfx/voice/vigiduel"
#macro sfx_voice_vigiangry "event:/sfx/voice/vigiangry"
#macro sfx_voice_myea "event:/sfx/voice/myea"
#macro sfx_voice_pizzahead "event:/sfx/voice/pizzahead"
#macro sfx_voice_fakepepscream "event:/sfx/voice/fakepepscream"
#macro sfx_voice_fakepeppositive "event:/sfx/voice/fakepeppositive"
#macro sfx_voice_fakepepnegative "event:/sfx/voice/fakepepnegative"
#macro sfx_voice_peppermanlaugh "event:/sfx/voice/peppermanlaugh"
#macro sfx_voice_peppermansnicker "event:/sfx/voice/peppermansnicker"
#macro sfx_voice_peppermanscared "event:/sfx/voice/peppermanscared"
#macro sfx_voice_brickok "event:/sfx/voice/brickok"
#macro sfx_voice_yodeling "event:/sfx/voice/yodeling"
#macro sfx_voice_pigphoto "event:/sfx/voice/pigphoto"
#macro sfx_voice_muffledscream "event:/sfx/voice/muffledscream"
#macro sfx_voice_transfo "event:/sfx/voice/transfo"
#macro sfx_voice_outtransfo "event:/sfx/voice/outtransfo"
#macro sfx_voice_hurt "event:/sfx/voice/hurt"
#macro sfx_voice_pizzagranny "event:/sfx/voice/pizzagranny"
#macro sfx_voice_geromegot "event:/sfx/voice/geromegot"
#macro sfx_voice_gusok "event:/sfx/voice/gusok"
#macro sfx_voice_mrstick "event:/sfx/voice/mrstick"
#macro sfx_voice_mrsticklaugh "event:/sfx/voice/mrsticklaugh"
#macro sfx_voice_pig "event:/sfx/voice/pig"

#macro sfx_jump "event:/sfx/pep/jump"
#macro sfx_punch "event:/sfx/pep/punch"
#macro sfx_screamboss "event:/sfx/pep/screamboss"
#macro sfx_pistolstart "event:/sfx/pep/pistolstart"
#macro sfx_pistolshot "event:/sfx/pep/pistolshot"
#macro sfx_revolvercharge "event:/sfx/pep/revolvercharge"
#macro sfx_revolverbigshot "event:/sfx/pep/revolverBIGshot"
#macro sfx_groundpound "event:/sfx/pep/groundpound"
#macro sfx_bumpwall "event:/sfx/pep/bumpwall"
#macro sfx_shotgunload "event:/sfx/pep/shotgunload"
#macro sfx_hurt "event:/sfx/pep/hurt"
#macro sfx_slip "event:/sfx/pep/slip"
#macro sfx_slipend "event:/sfx/pep/slipend"
#macro sfx_slipbump "event:/sfx/pep/slipbump"
#macro sfx_stepinshit "event:/sfx/pep/stepinshit"
#macro sfx_playerstep "event:/sfx/pep/step"
#macro sfx_taunt "event:/sfx/pep/taunt"
#macro sfx_break "event:/sfx/pep/break"
#macro sfx_machslideboost "event:/sfx/pep/machslideboost"
#macro sfx_splat "event:/sfx/pep/splat"
#macro sfx_superjumpcancel "event:/sfx/pep/superjumpcancel"
#macro sfx_backslide "event:/sfx/pep/backslide"
#macro sfx_supertaunt "event:/sfx/pep/supertaunt"
#macro sfx_gotsupertaunt "event:/sfx/pep/gotsupertaunt"
#macro sfx_gravecorpsestart "event:/sfx/pep/gravecorpsestart"
#macro sfx_gravecorpse "event:/sfx/pep/gravecorpse"
#macro sfx_cheesejump "event:/sfx/pep/cheesejump"
#macro sfx_box "event:/sfx/pep/box"
#macro sfx_jetpackjump "event:/sfx/pep/jetpackjump"
#macro sfx_suplexdash "event:/sfx/pep/suplexdash"
#macro sfx_playerjohnghost "event:/sfx/pep/johnghost"
#macro sfx_parry "event:/sfx/pep/parry"
#macro sfx_mach "event:/sfx/pep/mach"
#macro sfx_mach2bump "event:/sfx/pep/mach2bump"
#macro sfx_machroll "event:/sfx/pep/machroll"
#macro sfx_pizzapepper "event:/sfx/pep/pizzapepper"
#macro sfx_ghostspeed "event:/sfx/pep/ghostspeed"
#macro sfx_freefall "event:/sfx/pep/freefall"
#macro sfx_rollgetup "event:/sfx/pep/rollgetup"
#macro sfx_tumble "event:/sfx/pep/tumble"
#macro sfx_uppercut "event:/sfx/pep/uppercut"
#macro sfx_dive "event:/sfx/pep/dive"
#macro sfx_crouchslide "event:/sfx/pep/crouchslide"
#macro sfx_animatronic "event:/sfx/pep/animatronic"
#macro sfx_fireass "event:/sfx/pep/fireass"
#macro sfx_superjump "event:/sfx/pep/superjump"
#macro sfx_burn "event:/sfx/pep/burn"
#macro sfx_bombbounce "event:/sfx/pep/bombbounce"
#macro sfx_bombfuse "event:/sfx/pep/bombfuse"
#macro sfx_pray "event:/sfx/pep/pray"
#macro sfx_rampjump "event:/sfx/pep/rampjump"
#macro sfx_crossloop "event:/sfx/pep/cross"
#macro sfx_ghostintro "event:/sfx/pep/ghostintro"
#macro sfx_shotgunshot "event:/sfx/pep/shotgunshot"

#macro sfx_pepperman_shoulderbash "event:/sfx/pepperman/shoulderbash"
#macro sfx_pepperman_groundpound "event:/sfx/pepperman/groundpound"
#macro sfx_pepperman_groundpoundjump "event:/sfx/pepperman/groundpoundjump"
#macro sfx_pepperman_groundpoundbump "event:/sfx/pepperman/groundpoundbump"
#macro sfx_pepperman_turn "event:/sfx/pepperman/turn"
#macro sfx_pepperman_artdude "event:/sfx/pepperman/artdude"
#macro sfx_pepperman_statueappear "event:/sfx/pepperman/statueappear"
#macro sfx_pepperman_statuedestroy "event:/sfx/pepperman/statuedestroy"
#macro sfx_pepperman_knightappear "event:/sfx/pepperman/knightappear"
#macro sfx_pepperman_knightslide "event:/sfx/pepperman/knightslide"
#macro sfx_pepperman_shrink "event:/sfx/pepperman/shrink"

#macro sfx_vigilante_throw "event:/sfx/vigilante/throw"
#macro sfx_vigilante_flamestart "event:/sfx/vigilante/flamestart"
#macro sfx_vigilante_flamethrower "event:/sfx/vigilante/flamethrower"
#macro sfx_vigilante_mach1 "event:/sfx/vigilante/mach1"
#macro sfx_vigilante_slide "event:/sfx/vigilante/slide"
#macro sfx_vigilante_uziprep "event:/sfx/vigilante/uziprep"
#macro sfx_vigilante_order "event:/sfx/vigilante/order"
#macro sfx_vigilante_finalshot "event:/sfx/vigilante/finalshot"
#macro sfx_vigilante_bazookatrail "event:/sfx/vigilante/bazookatrail"
#macro sfx_vigilante_ghost "event:/sfx/vigilante/ghostloop"
#macro sfx_vigilante_cowstomp "event:/sfx/vigilante/cowstomp"
#macro sfx_vigilante_cowdead "event:/sfx/vigilante/cowdead"

#macro sfx_spin "event:/sfx/noise/spin"
#macro sfx_skatestart "event:/sfx/noise/skatestart"
#macro sfx_skateloop "event:/sfx/noise/skateloop"
#macro sfx_skateturn "event:/sfx/noise/skateturn"
#macro sfx_jetpackstart "event:/sfx/noise/jetpackstart"
#macro sfx_jetpackspin "event:/sfx/noise/jetpackspin"
#macro sfx_jetpackloop "event:/sfx/noise/jetpackloop"
#macro sfx_balloon "event:/sfx/noise/balloon"
#macro sfx_droptrap "event:/sfx/noise/droptrap"
#macro sfx_fightball "event:/sfx/noise/fightball"
#macro sfx_machslide "event:/sfx/noise/machslide"
#macro sfx_pogo "event:/sfx/noise/pogo"
#macro sfx_noisecrusher "event:/sfx/noise/noisecrusher"
#macro sfx_noisebombbounce "event:/sfx/noise/bombbounce"
#macro sfx_giantballoon1 "event:/sfx/noise/giantballoon1"
#macro sfx_giantballoon2 "event:/sfx/noise/giantballoon2"
#macro sfx_skatealone "event:/sfx/noise/skatealone"
#macro sfx_woag "event:/sfx/noise/woag"

#macro sfx_fakepep_bodyslam "event:/sfx/fakepep/bodyslam"
#macro sfx_fakepep_mach "event:/sfx/fakepep/mach"
#macro sfx_fakepep_superjump "event:/sfx/fakepep/superjump"
#macro sfx_fakepep_superjumpclonerelease "event:/sfx/fakepep/superjumpclonerelease"
#macro sfx_fakepep_grab "event:/sfx/fakepep/grab"
#macro sfx_fakepep_headoff "event:/sfx/fakepep/headoff"
#macro sfx_fakepep_flailing "event:/sfx/fakepep/flailing"
#macro sfx_fakepep_deform "event:/sfx/fakepep/deform"
#macro sfx_fakepep_reform "event:/sfx/fakepep/reform"
#macro sfx_fakepep_headthrow "event:/sfx/fakepep/headthrow"
#macro sfx_fakepep_taunt "event:/sfx/fakepep/taunt"
#macro sfx_fakepep_chasebegin "event:/sfx/fakepep/chasebegin"
#macro sfx_fakepep_chase "event:/sfx/fakepep/chase"
#macro sfx_fakepep_step "event:/sfx/fakepep/step"

#macro sfx_pizzaface_shower "event:/sfx/pizzaface/shower"
#macro sfx_pizzaface_ram "event:/sfx/pizzaface/ram"
#macro sfx_pizzaface_spit "event:/sfx/pizzaface/spit"
#macro sfx_pizzaface_laugh "event:/sfx/pizzaface/laugh"
#macro sfx_pizzaface_jump "event:/sfx/pizzaface/jump"
#macro sfx_pizzaface_open "event:/sfx/pizzaface/open"
#macro sfx_pizzaface_moving "event:/sfx/pizzaface/moving"
#macro sfx_pizzahead_haywire "event:/sfx/pizzahead/haywire"
#macro sfx_pizzahead_jump "event:/sfx/pizzahead/jump"
#macro sfx_pizzahead_bigpunch "event:/sfx/pizzahead/bigpunch"
#macro sfx_pizzahead_swinging "event:/sfx/pizzahead/swinging"
#macro sfx_pizzahead_swingstart "event:/sfx/pizzahead/swingstart"
#macro sfx_pizzahead_bigpunchstart "event:/sfx/pizzahead/bigpunchstart"
#macro sfx_pizzahead_giantstomp "event:/sfx/pizzahead/giantstomp"
#macro sfx_pizzahead_tvthrow "event:/sfx/pizzahead/tvthrow"
#macro sfx_pizzahead_spin "event:/sfx/pizzahead/spin"
#macro sfx_pizzahead_grablevel "event:/sfx/pizzahead/grablevel"
#macro sfx_pizzahead_fishing "event:/sfx/pizzahead/fishing"
#macro sfx_pizzahead_ratball "event:/sfx/pizzahead/ratball"
#macro sfx_pizzahead_step "event:/sfx/pizzahead/step"
#macro sfx_pizzahead_medievalbringup "event:/sfx/pizzahead/medievalbringup"
#macro sfx_pizzahead_uzi "event:/sfx/pizzahead/uzi"
#macro sfx_pizzahead_throw "event:/sfx/pizzahead/throw"
#macro sfx_pizzahead_medievalprojectile "event:/sfx/pizzahead/medievalprojectile"
#macro sfx_pizzahead_recover "event:/sfx/pizzahead/recover"
#macro sfx_pizzahead_beatdown "event:/sfx/pizzahead/beatdown"
#macro sfx_pizzahead_finale "event:/sfx/pizzahead/finale"
#macro sfx_pizzahead_finaleexplosion "event:/sfx/pizzahead/finaleexplosion"
#macro sfx_pizzahead_tvbounce "event:/sfx/pizzahead/tvbounce"
#macro sfx_pizzahead_cog "event:/sfx/pizzahead/cog"

#macro sfx_enemyscream "event:/sfx/voice/enemyrarescream"
#macro sfx_escapespawn "event:/sfx/enemies/escapespawn"
#macro sfx_killingblow "event:/sfx/enemies/killingblow"
#macro sfx_killenemy "event:/sfx/enemies/kill"
#macro sfx_stompenemy "event:/sfx/enemies/stomp"
#macro sfx_enemyprojectile "event:/sfx/enemies/projectile"
#macro sfx_rancherpistol "event:/sfx/enemies/rancherpistol"
#macro sfx_minijohnpunch "event:/sfx/enemies/minijohnpunch"
#macro sfx_pizzardelectricity "event:/sfx/enemies/pizzardelectricity"
#macro sfx_coughing "event:/sfx/enemies/coughing"
#macro sfx_ufolivelaser "event:/sfx/enemies/ufolivelaser"
#macro sfx_charge "event:/sfx/enemies/charge"
#macro sfx_batwing "event:/sfx/enemies/batwing"
#macro sfx_presentfall "event:/sfx/enemies/presentfall"
#macro sfx_badrat "event:/sfx/enemies/badrat"
#macro sfx_piranha "event:/sfx/enemies/piranha"
#macro sfx_ninjakicks "event:/sfx/enemies/ninjakicks"
#macro sfx_pickledance "event:/sfx/enemies/pickledance"
#macro sfx_cannongoblin "event:/sfx/enemies/cannongoblin"
#macro sfx_noisegoblinbow "event:/sfx/enemies/noisegoblinbow"
#macro sfx_robotslapsteam "event:/sfx/enemies/robotslapsteam"
#macro sfx_banditochicken "event:/sfx/enemies/banditochicken"
#macro sfx_comingoutground "event:/sfx/enemies/comingoutground"
#macro sfx_treasureguy "event:/sfx/enemies/treasureguy"
#macro sfx_johnghost "event:/sfx/enemies/johnghost"
#macro sfx_burp "event:/sfx/enemies/burp"
#macro sfx_johndead "event:/sfx/enemies/johndead"
#macro sfx_fakesanta "event:/sfx/enemies/fakesanta"
#macro sfx_alarm "event:/sfx/enemies/alarm"
#macro sfx_homing "event:/sfx/enemies/homing"
#macro sfx_demonsuprise "event:/sfx/enemies/demonsuprise"
#macro sfx_demoncharge "event:/sfx/enemies/demoncharge"
#macro sfx_cloneattack "event:/sfx/enemies/cloneattack"
#macro sfx_axethrow "event:/sfx/enemies/axethrow"
#macro sfx_tribaldance "event:/sfx/enemies/tribaldance"
#macro sfx_hamkuffgrab "event:/sfx/enemies/hamkuffgrab"
#macro sfx_kingghost "event:/sfx/kingghost/loop"
#macro sfx_kingghost_move "event:/sfx/kingghost/move"
#macro sfx_monsters_cheese "event:/sfx/monsters/cheeseloop"
#macro sfx_monsters_puppetfly "event:/sfx/monsters/puppetfly"
#macro sfx_monsters_robotstep "event:/sfx/monsters/robotstep"
#macro sfx_monsters_sausagestep "event:/sfx/monsters/sausagestep"
#macro sfx_jumpscare "event:/sfx/enemies/jumpscare"

#macro sfx_barrelstart "event:/sfx/barrel/start"
#macro sfx_barrelslope "event:/sfx/barrel/slope"
#macro sfx_barrelslide "event:/sfx/barrel/slide"
#macro sfx_barrelbump "event:/sfx/barrel/bump"
#macro sfx_boxxedstep "event:/sfx/boxxed/step"
#macro sfx_boxxedflap "event:/sfx/boxxed/flap"
#macro sfx_boxxedspin "event:/sfx/boxxed/spin"
#macro sfx_mortdead "event:/sfx/mort/mortdead"
#macro sfx_mortside "event:/sfx/mort/side"
#macro sfx_mortup "event:/sfx/mort/up"
#macro sfx_mortdown "event:/sfx/mort/down"
#macro sfx_mortdoublejump "event:/sfx/mort/doublejump"
#macro sfx_mortpickup "event:/sfx/mort/mortpickup"
#macro sfx_morthook "event:/sfx/mort/hook"
#macro sfx_mortslap "event:/sfx/mort/mortslap"
#macro sfx_mortcube "event:/sfx/mort/cube"
#macro sfx_firemouth_start "event:/sfx/firemouth/start"
#macro sfx_firemouth_dash "event:/sfx/firemouth/dash"
#macro sfx_firemouth_jump "event:/sfx/firemouth/jump"
#macro sfx_cheesedstep "event:/sfx/cheese/step"
#macro sfx_cheesedjump "event:/sfx/cheese/jump"
#macro sfx_cheesedground "event:/sfx/cheese/ground"
#macro sfx_cheesedball "event:/sfx/cheese/ball"
#macro sfx_knightstart "event:/sfx/knight/start"
#macro sfx_knightslide "event:/sfx/knight/slide"
#macro sfx_knightdown "event:/sfx/knight/down"
#macro sfx_knightlose "event:/sfx/knight/lose"
#macro sfx_lighting "event:/sfx/knight/thunder"
#macro sfx_antigravstart "event:/sfx/antigrav/start"
#macro sfx_antigravend "event:/sfx/antigrav/end"
#macro sfx_antigravbump "event:/sfx/antigrav/bump"
#macro sfx_ratmount_mach "event:/sfx/ratmount/mach"
#macro sfx_ratmount_ball "event:/sfx/ratmount/ball"
#macro sfx_ratmount_groundpound "event:/sfx/ratmount/groundpound"
#macro sfx_ratmount_punch "event:/sfx/ratmount/punch"
#macro sfx_ratmount_walljump1 "event:/sfx/ratmount/walljump1"
#macro sfx_ratmount_walljump2 "event:/sfx/ratmount/walljump2"
#macro sfx_weeniestart "event:/sfx/weenie/start"
#macro sfx_weeniebump "event:/sfx/weenie/bump"

#macro sfx_ratdeflate "event:/sfx/rat/deflate"
#macro sfx_ratdeflateeat "event:/sfx/rat/deflateeat"
#macro sfx_ratgrabeat "event:/sfx/rat/grabeat"
#macro sfx_ratgrab "event:/sfx/rat/grab"
#macro sfx_ratbowling "event:/sfx/rat/ratbowling"
#macro sfx_ratsniff "event:/sfx/rat/ratsniff"
#macro sfx_ratdead "event:/sfx/rat/ratdead"

#macro sfx_bossdefeattonk "event:/sfx/misc/bossdefeattonk"
#macro sfx_windloop "event:/sfx/misc/windloop"
#macro sfx_explosion "event:/sfx/misc/explosion"
#macro sfx_breakblock "event:/sfx/misc/breakblock"
#macro sfx_golfpunch "event:/sfx/misc/golfpunch"
#macro sfx_transfo "event:/sfx/misc/transfo"
#macro sfx_detransfo "event:/sfx/misc/detransfo"
#macro sfx_waterslidesplash "event:/sfx/misc/waterslidesplash"
#macro sfx_watersplash "event:/sfx/misc/watersplash"
#macro sfx_checkpoint "event:/sfx/misc/checkpoint"
#macro sfx_blackoutpunch "event:/sfx/misc/blackoutpunch"
#macro sfx_golfbump "event:/sfx/misc/golfbump"
#macro sfx_collect "event:/sfx/misc/collect"
#macro sfx_collectpizza "event:/sfx/misc/collectpizza"
#macro sfx_collecttoppin "event:/sfx/misc/collecttoppin"
#macro sfx_collectgiantpizza "event:/sfx/misc/collectgiantpizza"
#macro sfx_bellcollect "event:/sfx/misc/bellcollect"
#macro sfx_bellcollectbig "event:/sfx/misc/bellcollectbig"
#macro sfx_versusscreen "event:/sfx/misc/versusscreen"
#macro sfx_cardcollect "event:/sfx/misc/cardcollect"
#macro sfx_bosskey "event:/sfx/misc/bosskey"
#macro sfx_switchstart "event:/sfx/misc/switchstart"
#macro sfx_switchend "event:/sfx/misc/switchend"
#macro sfx_bubblestation "event:/sfx/misc/bubblestation"
#macro sfx_timerbegin "event:/sfx/misc/timerbegin"
#macro sfx_timercount "event:/sfx/misc/timercount"
#macro sfx_timerend "event:/sfx/misc/timerend"
#macro sfx_piranhabite "event:/sfx/misc/piranhabite"
#macro sfx_mushroombounce "event:/sfx/misc/mushroombounce"
#macro sfx_mrstickhat "event:/sfx/misc/mrstickhat"
#macro sfx_door "event:/sfx/misc/door"
#macro sfx_elevatorstart "event:/sfx/misc/elevatorstart"
#macro sfx_keyunlock "event:/sfx/misc/keyunlock"
#macro sfx_teleporterstart "event:/sfx/misc/teleporterstart"
#macro sfx_teleporterend "event:/sfx/misc/teleporterend"
#macro sfx_lap2start "event:/sfx/misc/lap2start"
#macro sfx_cross "event:/sfx/misc/cross"
#macro sfx_cow "event:/sfx/misc/cow"
#macro sfx_cowkick "event:/sfx/misc/cowkick"
#macro sfx_rockbreak "event:/sfx/misc/rockbreak"
#macro sfx_dashpad "event:/sfx/misc/dashpad"
#macro sfx_taxibeep "event:/sfx/misc/taxibeep"
#macro sfx_taximove "event:/sfx/misc/taximove"
#macro sfx_policesiren "event:/sfx/misc/policesiren"
#macro sfx_cheers "event:/sfx/misc/cheers"
#macro sfx_honkhonk "event:/sfx/misc/honkhonk"
#macro sfx_secretfound "event:/sfx/misc/secretfound"
#macro sfx_toppinhelp "event:/sfx/misc/toppinhelp"
#macro sfx_foundtreasure "event:/sfx/misc/foundtreasure"
#macro sfx_breakmetal "event:/sfx/misc/breakmetal"
#macro sfx_balloonpop "event:/sfx/misc/balloonpop"
#macro sfx_bottlepop "event:/sfx/misc/bottlepop"
#macro sfx_superspring "event:/sfx/misc/superspring"
#macro sfx_pepbotkick "event:/sfx/misc/pepbotkick"
#macro sfx_kashing "event:/sfx/misc/kashing"
#macro sfx_kashingcombo "event:/sfx/misc/kashingcombo"
#macro sfx_toppingot "event:/sfx/misc/toppingot"
#macro sfx_gaterise "event:/sfx/misc/gaterise"
#macro sfx_mrpinch "event:/sfx/misc/mrpinch"
#macro sfx_hamkuff "event:/sfx/misc/hamkuff"
#macro sfx_escaperumble "event:/sfx/misc/escaperumble"
#macro sfx_spaceship "event:/sfx/misc/spaceship"
#macro sfx_cardflip "event:/sfx/misc/cardflip"
#macro sfx_ventilator "event:/sfx/misc/ventilator"
#macro sfx_trashjump1 "event:/sfx/misc/trashjump1"
#macro sfx_trashjump2 "event:/sfx/misc/trashjump2"
#macro sfx_captaingoblinshoot "event:/sfx/misc/captaingoblinshoot"
#macro sfx_captaingoblincrosshair "event:/sfx/misc/captaingoblincrosshair"
#macro sfx_golfjingle "event:/sfx/misc/golfjingle"
#macro sfx_bossbeaten "event:/sfx/misc/bossbeaten"
#macro sfx_galloping "event:/sfx/misc/galloping"
#macro sfx_bossvulnerable "event:/sfx/misc/bossvulnerable"
#macro sfx_secretenter "event:/sfx/misc/secretenter"
#macro sfx_secretexit "event:/sfx/misc/secretexit"
#macro sfx_lapenter "event:/sfx/misc/lapenter"
#macro sfx_ufo "event:/sfx/misc/ufo"
#macro sfx_clotheswitch "event:/sfx/misc/clotheswitch"
#macro sfx_beerhit "event:/sfx/misc/beerhit"
#macro sfx_beerbreak "event:/sfx/misc/beerbreak"
#macro sfx_breakdance "event:/sfx/misc/breakdance"
#macro sfx_breakdancemusic "event:/sfx/misc/breakdancemusic"
#macro sfx_elevatorsqueak "event:/sfx/misc/elevatorsqueak"
#macro sfx_breakice "event:/sfx/misc/breakice"
#macro sfx_breakicebig "event:/sfx/misc/breakicebig"
#macro sfx_sniff "event:/sfx/misc/sniff"
#macro sfx_sniffbump "event:/sfx/misc/sniffbump"
#macro sfx_thundercloud "event:/sfx/misc/thundercloud"
#macro sfx_computerswitch "event:/sfx/misc/computerswitch"
#macro sfx_pepgusswitch "event:/sfx/misc/pepgusswitch"
#macro sfx_mine "event:/sfx/misc/mine"
#macro sfx_instanttemp "event:/sfx/misc/instanttemp"
#macro sfx_racestart "event:/sfx/misc/racestart"
#macro sfx_winrace "event:/sfx/misc/winrace"
#macro sfx_loserace "event:/sfx/misc/loserace"
#macro sfx_pipestart "event:/sfx/pipe/start"
#macro sfx_pipebump "event:/sfx/pipe/bump"
#macro sfx_pipeend "event:/sfx/pipe/end"
#macro sfx_gusrun "event:/sfx/hub/gusrun"
#macro sfx_gusbrickfightball "event:/sfx/hub/gusbrickfightball"
#macro sfx_pepgustavointro "event:/sfx/intro/pepgustavointro"
#macro sfx_star "event:/sfx/ending/star"
#macro sfx_towercollapsetrack "event:/sfx/ending/towercollapsetrack"
#macro sfx_towercollapse "event:/sfx/ending/towercollapse"
#macro sfx_johnending "event:/sfx/ending/johnending"

// music
#macro mu_pizzatime "event:/music/pizzatime"
#macro mu_finalescape "event:/music/finalescape"
#macro mu_rank "event:/music/rank"
#macro mu_timesup "event:/music/timesup"
#macro mu_finalrank "event:/music/finalrank"
#macro mu_intro "event:/music/intro"
#macro mu_ending "event:/music/ending"
#macro mu_credits "event:/music/credits"
#macro mu_title "event:/music/title"
#macro mu_pause "event:/music/pause"

#macro mu_pillar "event:/music/pillarmusic"
#macro mu_tutorial "event:/music/tutorial"
#macro mu_hub "event:/music/hub"
#macro mu_finalhallway "event:/music/w5/finalhallway"
#macro mu_boss_pepperman "event:/music/boss/pepperman"
#macro mu_boss_vigilante "event:/music/boss/vigilante"
#macro mu_boss_noise "event:/music/boss/noise"
#macro mu_boss_noisette "event:/music/boss/noisette"
#macro mu_boss_fakepep "event:/music/boss/fakepep"
#macro mu_boss_pizzaface "event:/music/boss/pizzaface"
#macro mu_fakepepambient "event:/music/boss/fakepepambient"

#macro mu_entrance "event:/music/w1/entrance"
#macro mu_entrancesecret "event:/music/w1/entrancesecret"
#macro mu_medieval "event:/music/w1/medieval"
#macro mu_medievalsecret "event:/music/w1/medievalsecret"
#macro mu_ruin "event:/music/w1/ruin"
#macro mu_ruinsecret "event:/music/w1/ruinsecret"
#macro mu_dungeon "event:/music/w1/dungeon"
#macro mu_dungeonsecret "event:/music/w1/dungeonsecret"

#macro mu_desert "event:/music/w2/desert"
#macro mu_desertsecret "event:/music/w2/desertsecret"
#macro mu_farm "event:/music/w2/farm"
#macro mu_farmsecret "event:/music/w2/farmsecret"
#macro mu_graveyard "event:/music/w2/graveyard"
#macro mu_graveyardsecret "event:/music/w2/graveyardsecret"
#macro mu_saloon "event:/music/w2/saloon"
#macro mu_saloonsecret "event:/music/w2/saloonsecret"

#macro mu_beach "event:/music/w3/beach"
#macro mu_beachsecret "event:/music/w3/beachsecret"
#macro mu_forest "event:/music/w3/forest"
#macro mu_forestsecret "event:/music/w3/forestsecret"
#macro mu_golf "event:/music/w3/golf"
#macro mu_golfsecret "event:/music/w3/golfsecret"
#macro mu_space "event:/music/w3/space"
#macro mu_spacesecret "event:/music/w3/spacesecret"

#macro mu_freezer "event:/music/w4/freezer"
#macro mu_freezersecret "event:/music/w4/freezersecret"
#macro mu_industrial "event:/music/w4/industrial"
#macro mu_industrialsecret "event:/music/w4/industrialsecret"
#macro mu_sewer "event:/music/w4/sewer"
#macro mu_sewersecret "event:/music/w4/sewersecret"
#macro mu_street "event:/music/w4/street"
#macro mu_streetsecret "event:/music/w4/streetsecret"

#macro mu_chateau "event:/music/w5/chateau"
#macro mu_kidsparty "event:/music/w5/kidsparty"
#macro mu_kidspartysecret "event:/music/w5/kidspartysecret"
#macro mu_kidspartychase "event:/music/w5/kidspartychase"
#macro mu_war "event:/music/w5/war"
#macro mu_warsecret "event:/music/w5/warsecret"

// title cards
#macro mu_entrancetitle "event:/music/w1/entrancetitle"
#macro mu_medievaltitle "event:/music/w1/medievaltitle"
#macro mu_ruintitle "event:/music/w1/ruintitle"
#macro mu_dungeontitle "event:/music/w1/dungeontitle"
#macro mu_deserttitle "event:/music/w2/deserttitle"
#macro mu_saloontitle "event:/music/w2/saloontitle"
#macro mu_graveyardtitle "event:/music/w2/graveyardtitle"
#macro mu_farmtitle "event:/music/w2/farmtitle"
#macro mu_golftitle "event:/music/w3/golftitle"
#macro mu_foresttitle "event:/music/w3/foresttitle"
#macro mu_spacetitle "event:/music/w3/spacetitle"
#macro mu_beachtitle "event:/music/w3/beachtitle"
#macro mu_industrialtitle "event:/music/w4/industrialtitle"
#macro mu_freezertitle "event:/music/w4/freezertitle"
#macro mu_sewertitle "event:/music/w4/sewertitle"
#macro mu_streettitle "event:/music/w4/streettitle"
#macro mu_kidspartytitle "event:/music/w5/kidspartytitle"
#macro mu_wartitle "event:/music/w5/wartitle"
#macro mu_chateautitle "event:/music/w5/chateautitle"

#endregion
