event_inherited();
idle = true;
disx = 150;
landspr = spr_peasanto_idle;
idlespr = spr_peasanto_throwstart;
fallspr = spr_peasanto_idle;
stunfallspr = spr_peasanto_stun;
walkspr = spr_peasanto_walk;
turnspr = spr_peasanto_idle;
recoveryspr = spr_peasanto_stun;
grabbedspr = spr_peasanto_stun;
scaredspr = spr_peasanto_scared;
ragespr = spr_peasanto_flameattack;
spr_dead = spr_peasanto_dead;
sprite_index = walkspr;
