event_inherited();
trigger = 2;
idlespr = spr_menutv3_idle;
transspr = spr_menutv3_trans;
confirmspr = spr_menutv3_confirm;
selectedspr = spr_menutv3_selected;
clipspr = spr_menutv3_clip;
noisescale = 1;
noisexoffset = 76;
noiseyoffset = 115;
