targetDoor = "A";
depth = 100;
image_speed = 0;
level = "none";
world = 1;
pizza = false;
rank = "d";
group_arr = -4;
boss = false;
drawing = false;
targetDoor = "A";
msg = "";
highscore = 0;
secret_count = 0;
toppin = array_create(5, 0);
scr_hub_bg_init();
scr_create_uparrowhitbox();
titlecard_sprite = spr_titlecards;
titlecard_index = 0;
title_sprite = spr_titlecards_title;
title_index = 0;
title_music = "event:/music/w1/entrancetitle";
