grabbed = false;
hsp = 0;
vsp = 0;
grav = 0.5;
flash = true;
hp = 0;
grounded = true;
state = 0; // not an enum
mask_index = spr_player_mask;
image_speed = 0.4;
depth = 1;
platformid = -4;
hsp_carry = 0;
vsp_carry = 0;
