scr_initenemy();
image_speed = 0.35;
depth = 0;
state = states.walk;
flash = false;
important = false;
spr_dead = spr_grandpa_dead;
spr_palette = palette_cheeseslime;
paletteselect = 0;
grounded = true;
