event_inherited();
walkspr = spr_stick_towercollapse_walk;
idlespr = spr_stick_towercollapse_idle;
isgustavo = false;
snotty = false;
image_speed = 0.35;
use_palette = false;
spr_palette = noone;
paletteselect = 0;
palettetexture = noone;
