text = "THIS IS A WIP BUILD,\nA BUNCH OF STUFF IS MISSING\nOR WILL BE CHANGED LATER!\nCONSIDER THIS AN EGGPLANT FLAVORED\nAPPETIZER OF WHATS TO COME!";
xorigin = 1;
yorigin = 0;
font = global.smallfont;
