scr_initenemy();
grav = 0.5;
hsp = 0;
vsp = 0;
grounded = false;
movespeed = 2;
hitboxcreate = false;
state = states.walk;
image_speed = 0.35;
sign_id = -4;
spr_dead = spr_piraneapple_dead;
alarm[1] = 10;
mask_index = spr_player_mask;
platformid = -4;
hsp_carry = 0;
vsp_carry = 0;
hamspotted = false;
