hsp = random_range(2, 6);
vsp = random_range(2, 6);
dir1 = choose(1, -1);
dir2 = choose(1, -1);
shake = 0;
image_speed = 0;
image_index = random_range(0, image_number - 1);
image_angle = random_range(0, 360);
depth = -250;
