image_speed = 0.35;
alarm[0] = 2;
alarm[2] = 2;
alarm[3] = 2;
playerid = -4;
last_current_time = current_time;
timer = current_time;
xoffset = 0;
yoffset = 0;
depth = -12;
snd = fmod_event_create_instance("event:/sfx/pep/cross");
fmod_event_instance_play(snd);
